on: workflow_dispatch
name: bridgecommand_make_repo
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
      
    steps:  
    - uses: actions/checkout@v4

    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install deps
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf -y install docker
    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
        
    
      #with:
       # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        #fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    
    
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.flathub.bridgecommand
        manifest-path: org.flathub.Bridgecommand.yml
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}


        
    - name: See
      run: |   
        ls -l
    - name: Send to my git
      run: |
        git config --global --add safe.directory /__w/bridgecommand_flatpak/bridgecommand_flatpak
        git config --global --add safe.directory /github/workspace
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -f repo/*
        git commit -m "I am commited"
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin main     
        
      # https://github.com/ad-m/github-push-action
      # https://github.com/orgs/community/discussions/68891
      # https://github.com/orgs/community/discussions/25234
